stages:
  - test
  - build
  - deploy

include:
  - component: gitlab.dot.co.id/cicd-components/sonarqube/cli@main
    inputs:
      run-on: /^develop$/i
      sonar-project-key: playground_boilerplates_vite-admiral_d40f7698-bcac-4f02-b16a-f872446bf1df
      sonar-project-name: dot-boilerplate-vite-admiral


.build:docker_image:
  stage: build
  image: docker:20.10
  tags: [dot]
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - cp $DOTENV_FILE_PATH .env.local
    - docker build
      --progress plain
      --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}${CI_COMMIT_SHORT_SHA}
      --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}
      .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}

build_develop:docker_image:
  extends: .build:docker_image
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  variables:
    DOTENV_FILE_PATH: $DOTENV_DEVELOP

build_mr:docker_image:
  extends: .build:docker_image
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^develop$/i'
  script:
    - cp "$DOTENV_DEVELOP" .env.local
    - docker build
        --progress plain
        --tag "${CI_REGISTRY_IMAGE}:${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}_mr"
        --file Dockerfile
        .

deploy_develop:docker:
  stage: deploy
  image: asia.gcr.io/dot-gitlab-runner/ansible:2.9.21
  tags: [dot]
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  environment:
    name: develop
    url: https://vite-admiral-blrplt.dot.co.id
  before_script:
    - chmod 600 $ANSIBLE_KEY_FILE
    - ansible-galaxy collection install community.docker:==3.4.0
  script:
    - ansible-playbook --private-key $ANSIBLE_KEY_FILE -i deploy/hosts -v deploy/develop.yml
